/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BackupFinal.java
 *
 * Created on Nov 6, 2013, 11:10:03 AM
 */

package mainpr;

import java.io.File;
import java.sql.ResultSet;

/**
 *
 * @author USER2
 */
public class BackupFinal extends javax.swing.JFrame {
File op;
String ad="";
    /** Creates new form BackupFinal */
    public BackupFinal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\project\\IMAGG\\backup-splash.jpg")); // NOI18N
        jLabel1.setBounds(0, 0, 470, 300);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        l1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        l1.setForeground(new java.awt.Color(153, 153, 153));
        l1.setText("USER");
        l1.setBounds(200, 20, 50, 17);
        jLayeredPane1.add(l1, javax.swing.JLayeredPane.PALETTE_LAYER);

        t1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        t1.setForeground(new java.awt.Color(102, 102, 102));
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t1MouseClicked(evt);
            }
        });
        t1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t1CaretUpdate(evt);
            }
        });
        t1.setBounds(260, 20, 200, 20);
        jLayeredPane1.add(t1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Address");
        jLabel2.setBounds(200, 60, 60, 17);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.PALETTE_LAYER);

        t2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        t2.setForeground(new java.awt.Color(102, 102, 102));
        t2.setEnabled(false);
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                t2MouseClicked(evt);
            }
        });
        t2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t2CaretUpdate(evt);
            }
        });
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        t2.setBounds(260, 60, 200, 20);
        jLayeredPane1.add(t2, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/ghj.png"))); // NOI18N
        jLabel4.setText("Create Backup");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jLabel4.setBounds(160, 110, 200, 110);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.PALETTE_LAYER);

        l3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        l3.setForeground(new java.awt.Color(102, 102, 102));
        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/index.jpeg"))); // NOI18N
        l3.setText("Restore");
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        l3.setBounds(170, 220, 120, 70);
        jLayeredPane1.add(l3, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/black.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jLabel3.setBounds(350, 200, 110, 100);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed

    }//GEN-LAST:event_t2ActionPerformed

    private void t2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MouseClicked
t1.setEnabled(false);
t2.setEnabled(true);
    }//GEN-LAST:event_t2MouseClicked

    private void t1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MouseClicked
   t2.setEnabled(false);
t1.setEnabled(true);
    }//GEN-LAST:event_t1MouseClicked

    private void t1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t1CaretUpdate
        ad="'c:/Users/USER"+t1.getText()+"/Desktop/";
    }//GEN-LAST:event_t1CaretUpdate

    private void t2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t2CaretUpdate
        ad="'"+t2.getText();
    }//GEN-LAST:event_t2CaretUpdate

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
    String q=t1.getText();

        ResultSet rs=cons.startq("show Tables");
        try {
            while (rs.next()) {

                ResultSet RS= cons.startq("select *from "+rs.getString("Tables_in_redfins")+" into outfile "+ad+rs.getString("Tables_in_redfins")+".txt'  fields terminated by ','  ;");
            }
        }
        catch (Exception e)
        {
            System.out.print(e);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
  ResultSet rs=cons.startq("show Tables;");
        try {
           while( rs.next()){
cons.start("delete from "+rs.getString("Tables_in_redfins")+";");
                cons.start("Load data local infile "+ad+rs.getString("Tables_in_redfins")+".txt' into TABLE "+rs.getString("Tables_in_redfins")+" fields terminated by ','; ");
            }
        } catch (Exception e) {
System.out.print(e);
        }        // TODO add your handling code        // TODO add your handling code here:
    }//GEN-LAST:event_l3MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        new FourWay().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BackupFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables

}
