/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FourWay.java
 *
 * Created on Nov 11, 2013, 11:40:05 AM
 */

package mainpr;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author USER2
 */
public class FourWay extends javax.swing.JFrame {
int a=0,b=128,c=0;
  ActionListener taskPerformer ;
    ActionListener taskPerformer1;
    int delay = 10;
    int delay1 = 10;
    static int jk=0;
    /** Creates new form FourWay */
    public FourWay() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        j5 = new javax.swing.JLabel();
        j6 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        j7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        j8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        l2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/teacher-icon.gif"))); // NOI18N
        l2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l2MouseExited(evt);
            }
        });
        l2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                l2MouseMoved(evt);
            }
        });
        l2.setBounds(490, 70, 94, 98);
        jLayeredPane1.add(l2, javax.swing.JLayeredPane.PALETTE_LAYER);

        l3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        l3.setForeground(new java.awt.Color(51, 51, 51));
        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/Delete Teacher.jpeg"))); // NOI18N
        l3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l3MouseExited(evt);
            }
        });
        l3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                l3MouseMoved(evt);
            }
        });
        l3.setBounds(490, 200, 102, 114);
        jLayeredPane1.add(l3, javax.swing.JLayeredPane.PALETTE_LAYER);

        l4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        l4.setForeground(new java.awt.Color(51, 51, 51));
        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/Search.jpeg"))); // NOI18N
        l4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l4MouseExited(evt);
            }
        });
        l4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                l4MouseMoved(evt);
            }
        });
        l4.setBounds(500, 320, 82, 109);
        jLayeredPane1.add(l4, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/settings.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jLabel2.setBounds(40, 180, 130, 118);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.PALETTE_LAYER);

        j3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        j3.setForeground(new java.awt.Color(0, 153, 204));
        j3.setText("Save");
        j3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j3MouseMoved(evt);
            }
        });
        j3.setBounds(650, 90, 80, 60);
        jLayeredPane1.add(j3, javax.swing.JLayeredPane.PALETTE_LAYER);

        j4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        j4.setForeground(new java.awt.Color(0, 153, 204));
        j4.setText("Delete");
        j4.setBounds(650, 200, 80, 110);
        jLayeredPane1.add(j4, javax.swing.JLayeredPane.PALETTE_LAYER);

        j5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        j5.setForeground(new java.awt.Color(0, 153, 204));
        j5.setText("Search");
        j5.setBounds(660, 320, 80, 110);
        jLayeredPane1.add(j5, javax.swing.JLayeredPane.PALETTE_LAYER);

        j6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        j6.setForeground(new java.awt.Color(0, 153, 204));
        j6.setText("Settings");
        j6.setBounds(230, 180, 90, 100);
        jLayeredPane1.add(j6, javax.swing.JLayeredPane.PALETTE_LAYER);

        l8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        l8.setForeground(new java.awt.Color(51, 51, 51));
        l8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/cal.jpg"))); // NOI18N
        l8.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        l8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l8MouseExited(evt);
            }
        });
        l8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                l8MouseMoved(evt);
            }
        });
        l8.setBounds(40, 320, 115, 120);
        jLayeredPane1.add(l8, javax.swing.JLayeredPane.PALETTE_LAYER);

        j2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        j2.setForeground(new java.awt.Color(0, 153, 204));
        j2.setText("Subtitution");
        j2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j2MouseMoved(evt);
            }
        });
        j2.setBounds(230, 320, 110, 110);
        jLayeredPane1.add(j2, javax.swing.JLayeredPane.PALETTE_LAYER);

        l1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        l1.setForeground(new java.awt.Color(51, 51, 51));
        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/ghj.png"))); // NOI18N
        l1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        l1.setIconTextGap(6);
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
        });
        l1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                l1MouseMoved(evt);
            }
        });
        l1.setBounds(40, 70, 120, 100);
        jLayeredPane1.add(l1, javax.swing.JLayeredPane.PALETTE_LAYER);

        j1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        j1.setForeground(new java.awt.Color(0, 153, 204));
        j1.setText("Back Up");
        j1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j1MouseMoved(evt);
            }
        });
        j1.setBounds(230, 70, 100, 100);
        jLayeredPane1.add(j1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/ghjk.jpg"))); // NOI18N
        jLabel3.setBounds(0, 0, 830, 600);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/leave.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.setBounds(40, 450, 118, 118);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.PALETTE_LAYER);

        j7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        j7.setForeground(new java.awt.Color(0, 153, 204));
        j7.setText("Leave");
        j7.setBounds(230, 480, 70, 50);
        jLayeredPane1.add(j7, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/images.jpeg"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel4MouseMoved(evt);
            }
        });
        jLabel4.setBounds(490, 470, 102, 100);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel5.setText("jLabel5");
        jLabel5.setBounds(210, 250, 70, 30);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        j8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        j8.setForeground(new java.awt.Color(0, 153, 204));
        j8.setText("Sallary");
        j8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j8MouseMoved(evt);
            }
        });
        j8.setBounds(650, 460, 100, 100);
        jLayeredPane1.add(j8, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/tyu.PNG"))); // NOI18N
        jLabel6.setBounds(630, 10, 80, 72);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked

        new BackupFinal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l1MouseClicked

    private void l1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseMoved
j1.setVisible(true);

    }//GEN-LAST:event_l1MouseMoved

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
jk=0;
new mainframe().setVisible(true);
this.dispose();
    }//GEN-LAST:event_l2MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
        jk=1;
        new mainframe().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l3MouseClicked

    private void l4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseClicked
       jk=2;
         new mainframe().setVisible(true);
    }//GEN-LAST:event_l4MouseClicked

    private void l8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseClicked
this.dispose();
new Subtitutionfinal().setVisible(true);


    }//GEN-LAST:event_l8MouseClicked

    private void j1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1MouseMoved
l1.setVisible(true);
    }//GEN-LAST:event_j1MouseMoved

    private void l1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseExited
j1.setVisible(false);
 
    }//GEN-LAST:event_l1MouseExited

    private void j3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3MouseMoved
    // TODO add your handling code here:
    }//GEN-LAST:event_j3MouseMoved

    private void j2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_j2MouseMoved

    private void l8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseMoved
     j2.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_l8MouseMoved

    private void l2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseMoved
     j3.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_l2MouseMoved

    private void l3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseMoved
 j4.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_l3MouseMoved

    private void l4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseMoved
    j5.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_l4MouseMoved

    private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
 j6.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseMoved

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    j1.setVisible(false);      j7.setVisible(false);
       j2.setVisible(false);
          j3.setVisible(false);
             j4.setVisible(false);    j6.setVisible(false);
                j5.setVisible(false);
j8.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void l8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseExited
j2.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_l8MouseExited

    private void l2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseExited
j3.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_l2MouseExited

    private void l3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseExited
j4.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_l3MouseExited

    private void l4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseExited
j5.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_l4MouseExited

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
j6.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
       j7.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
j7.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       this.dispose();
        new leave().setVisible(true);
       
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
     this.dispose();
        new sett().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void j8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j8MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_j8MouseMoved

    private void jLabel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseMoved
       j8.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseMoved

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
    j8.setVisible(false);     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
  this.dispose();
        new salary().setVisible(true);
      
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FourWay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel j6;
    private javax.swing.JLabel j7;
    private javax.swing.JLabel j8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l8;
    // End of variables declaration//GEN-END:variables

}
