package mainpr;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * salary.java
 *
 * Created on Aug 31, 2013, 10:19:55 AM
 */

/**
 *
 * @author USER1
 */
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import sun.net.www.content.image.png;
public class salary extends javax.swing.JFrame {
    private String pf;

    /** Creates new form salary */

    public salary() {
        initComponents();
        setIcon();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        t13 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 22));
        jLabel14.setForeground(new java.awt.Color(51, 102, 0));
        jLabel14.setText("SALARY FORM");
        jLabel14.setBounds(110, 10, 220, 40);
        jLayeredPane1.add(jLabel14, javax.swing.JLayeredPane.PALETTE_LAYER);

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(490, 90, 90, 30);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.PALETTE_LAYER);

        jButton1.setText("update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(490, 130, 90, 30);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jButton3.setText("SHOW");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(490, 170, 90, 30);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.PALETTE_LAYER);

        jButton5.setText("DELETE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(490, 210, 90, 30);
        jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.PALETTE_LAYER);

        jButton4.setText("TOTAL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(490, 250, 90, 30);
        jLayeredPane1.add(jButton4, javax.swing.JLayeredPane.PALETTE_LAYER);

        jButton6.setText("Clear All");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.setBounds(490, 300, 90, 30);
        jLayeredPane1.add(jButton6, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11));
        jLabel4.setForeground(new java.awt.Color(51, 102, 0));
        jLabel4.setText("TEACHER ID");
        jLabel4.setBounds(10, 100, 71, 15);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.PALETTE_LAYER);

        t1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t1CaretUpdate(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        t1.setBounds(250, 100, 160, 20);
        jLayeredPane1.add(t1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11));
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setText("Basic Sallary");
        jLabel1.setBounds(10, 130, 70, 15);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.PALETTE_LAYER);
        t2.setBounds(250, 130, 160, 20);
        jLayeredPane1.add(t2, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11));
        jLabel6.setForeground(new java.awt.Color(51, 102, 0));
        jLabel6.setText("DEARLY ALLOWANCE");
        jLabel6.setBounds(10, 170, 126, 15);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.PALETTE_LAYER);

        t.setEditable(false);
        t.setBounds(250, 160, 160, 20);
        jLayeredPane1.add(t, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11));
        jLabel7.setForeground(new java.awt.Color(51, 102, 0));
        jLabel7.setText("HOUSE RENT ALLOWENCE");
        jLabel7.setBounds(10, 210, 156, 15);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.PALETTE_LAYER);

        t6.setEditable(false);
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        t6.setBounds(250, 200, 160, 20);
        jLayeredPane1.add(t6, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11));
        jLabel9.setForeground(new java.awt.Color(51, 102, 0));
        jLabel9.setText("LIC");
        jLabel9.setBounds(10, 240, 18, 15);
        jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.PALETTE_LAYER);

        t8.setEditable(false);
        t8.setBounds(250, 240, 160, 20);
        jLayeredPane1.add(t8, javax.swing.JLayeredPane.PALETTE_LAYER);

        t9.setEditable(false);
        t9.setBounds(250, 270, 160, 20);
        jLayeredPane1.add(t9, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11));
        jLabel5.setForeground(new java.awt.Color(51, 102, 0));
        jLabel5.setText("PROVIDENT FUND");
        jLabel5.setBounds(10, 270, 107, 15);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11));
        jLabel10.setForeground(new java.awt.Color(51, 102, 0));
        jLabel10.setText("LEAVE TRAVEL ALLOWANCE");
        jLabel10.setBounds(10, 310, 167, 15);
        jLayeredPane1.add(jLabel10, javax.swing.JLayeredPane.PALETTE_LAYER);
        t3.setBounds(250, 310, 160, 20);
        jLayeredPane1.add(t3, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11));
        jLabel11.setForeground(new java.awt.Color(51, 102, 0));
        jLabel11.setText("MEDICAL ALLOWANCE");
        jLabel11.setBounds(10, 350, 134, 15);
        jLayeredPane1.add(jLabel11, javax.swing.JLayeredPane.PALETTE_LAYER);
        t4.setBounds(250, 350, 160, 20);
        jLayeredPane1.add(t4, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11));
        jLabel12.setForeground(new java.awt.Color(51, 102, 0));
        jLabel12.setText("CONVEYANCE ALLOWANCE");
        jLabel12.setBounds(10, 380, 165, 15);
        jLayeredPane1.add(jLabel12, javax.swing.JLayeredPane.PALETTE_LAYER);
        t5.setBounds(250, 380, 160, 20);
        jLayeredPane1.add(t5, javax.swing.JLayeredPane.PALETTE_LAYER);

        t13.setEditable(false);
        t13.setBounds(250, 420, 160, 20);
        jLayeredPane1.add(t13, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 13));
        jLabel13.setForeground(new java.awt.Color(51, 102, 0));
        jLabel13.setText("NET PAYABLE SALARY");
        jLabel13.setBounds(10, 420, 149, 18);
        jLayeredPane1.add(jLabel13, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Public\\IMAGG\\six figure salary negotiations.jpg")); // NOI18N
        jLabel2.setBounds(0, 0, 590, 480);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER2\\Desktop\\tyu.PNG")); // NOI18N
        jLabel8.setBounds(480, 10, 80, 72);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Public\\IMAGG\\black.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jLabel3.setBounds(470, 350, 110, 100);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
ResultSet rs=cons.startq("select * from deduct;");

try{
    rs.next();
t6.setText(rs.getString("hra"));
t8.setText(rs.getString("insurance"));
t.setText(rs.getString("da"));
t9.setText(rs.getString("pf"));
}


catch (Exception e)
{

}
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
ImageIcon icon = new ImageIcon( getClass().getResource( "C:\\Users\\Public\\IMAGG\\icon.png" ) );
              setIconImage( icon.getImage() );        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double n1=Double.parseDouble(t1.getText());
        double n2=Double.parseDouble(t2.getText());
        double n3=Double.parseDouble(t3.getText());
        double n4=Double.parseDouble(t4.getText());
        double n5=Double.parseDouble(t5.getText());

        cons.start("insert into salary values("+n1+","+n2+","+n3+","+n4+","+n5+");");
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double n1=Double.parseDouble(t1.getText());
        double n2=Double.parseDouble(t2.getText());
        double n3=Double.parseDouble(t3.getText());
        double n4=Double.parseDouble(t4.getText());
        double n5=Double.parseDouble(t5.getText());
        ResultSet rs=cons.startq("Select * from td;");
        try {
            while (rs.next()) {
                if (n1 == rs.getInt("tid")) {
                    cons.start("delete from salary where tid="+n1+";");
                    cons.start("insert into salary values("+n1+","+n2+","+n3+","+n4+","+n5+");");
                }


            }
        } catch (Exception e) {
            System.out.print(e);
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        double n1=Double.parseDouble(t1.getText());
        ResultSet ss = cons.startq("select * from salary where tid="+n1+";");

        try {
            while (ss.next()) {


                String a2=ss.getString("bsal");

                String a3=ss.getString("lta");
                String a4=ss.getString("ma");
                String a5=ss.getString("ca");


                t2.setText(a2);
                t3.setText(a3);
                t4.setText(a4);
                t5.setText(a5);

            }
            // TODO add your handling code here:
            // TODO add your handling code here:
        } catch (Exception e) {
            System.out.print(e);
        }
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int a=Integer.parseInt(t1.getText());

        cons.start("delete from salary where tid="+a+");");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed


        double n2=Double.parseDouble(t2.getText());
        double n3=Double.parseDouble(t3.getText());
        double n4=Double.parseDouble(t4.getText());
        double n5=Double.parseDouble(t5.getText());
        double n6=Double.parseDouble(t6.getText());
        double n8=Double.parseDouble(t8.getText());
        double n9=Double.parseDouble(t9.getText());
        double n=Double.parseDouble(t.getText());

        double a=0;
        double b=0;
        double lic=0;
        double d=0;
        double e=0;
        double f=0;
        double g=0;
        double h=0;
        double i=0;

        a=n2+(n2*n)/100;
        a=a+n6;
        a=a-(n2*n8)/100;
        a=a-(a*n9)/100;
        a=a+n3+n4+n5;
        t13.setText(a+"");
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        t1.setText("");

        t3.setText("");

        t.setText("");
        t6.setText("");

        t8.setText("");
        t9.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        // TODO add your handling code here:
}//GEN-LAST:event_jButton6ActionPerformed

    private void t1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t1CaretUpdate

    }//GEN-LAST:event_t1CaretUpdate

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t1ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t6ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        new FourWay().setVisible(true);
        this.dispose();
}//GEN-LAST:event_jLabel3MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField t;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage("icon.gif"));
    }

   // private void setIconImage() {
        //throw new UnsupportedOperationException("Not yet implemented");


}
