/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ssssss.java
 *
 * Created on Oct 26, 2013, 2:05:42 PM
 */

package mainpr;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author USER1
 */
public class ssssss extends javax.swing.JFrame {

    /** Creates new form ssssss */
    public ssssss() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        t2 = new javax.swing.JPasswordField();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SSI LOGIN");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Public\\Downloads\\Simple-Login-Form.jpg")); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setBounds(0, 0, 600, 300);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        t2.setBorder(null);
        t2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t2CaretUpdate(evt);
            }
        });
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        t2.setBounds(370, 165, 170, 20);
        jLayeredPane1.add(t2, javax.swing.JLayeredPane.PALETTE_LAYER);

        t1.setBorder(null);
        t1.setBounds(370, 105, 170, 20);
        jLayeredPane1.add(t1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jLabel2.setBounds(380, 210, 130, 30);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel3.setText("jLabel3");
        jLabel3.setBounds(370, 270, 180, -1);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Change Username and Password ?");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jLabel4.setBounds(340, 240, 210, 20);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.MODAL_LAYER);

        l5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10));
        l5.setForeground(new java.awt.Color(255, 255, 255));
        l5.setBounds(380, 194, 130, 10);
        jLayeredPane1.add(l5, javax.swing.JLayeredPane.MODAL_LAYER);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Public\\IMAGG\\gh.png")); // NOI18N
        jLabel5.setBounds(20, 20, 280, 270);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.MODAL_LAYER);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("     SSI Corporation");
        jLabel6.setBounds(80, 230, 160, -1);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
   String q=t1.getText().toLowerCase();
        String w=t2.getText();

        try {
            Class.forName("java.sql.DriverManager");
            Connection c = (Connection) DriverManager.getConnection("jdbc:mySQL://localhost:3306/redfins", "root", "rrmps");
            Statement s = (Statement) c.createStatement();
            Statement s1 = (Statement) c.createStatement();
            Statement s2 = (Statement) c.createStatement();
            String k = "select * from login ;";
           //  JOptionPane.showMessageDialog(null, k);

            ResultSet rs = s.executeQuery(k);
           int j=0;

            while(j<=rs.getRow())
            {
                rs.next();
                String jk=rs.getString("tid");
                String a=rs.getString("ename");
                String b=rs.getString("epass");


                if(q.equals(a) && w.equals(b))
                {
                    new FourWay().setVisible(true);
                    this.dispose();
                    j++;

                   String k2 = "insert into detect values("+jk+",(Select Now()),(select now()));";
           s2.executeUpdate(k2);
                } else {
 // JOptionPane.showMessageDialog(null,"enter valid username and password");
                    String gg="fngjhd";
                }

            }

if(j>rs.getRow())
JOptionPane.showMessageDialog(null,"enter valid username and password");
        }


        catch (Exception e) {
            //JOptionPane.showMessageDialog(null,"enter valid username and password");
            //JOptionPane.showMessageDialog(this,e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void t2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t2CaretUpdate
 if(t2.getText().equals(""))
 {
      l5.setText("");
 }
     else {
        String d=t2.getText().toUpperCase();
        if(t2.getText().equals(d))
            {
      l5.setText("CAPS LOCK IS ON");
   }}
    }//GEN-LAST:event_t2CaretUpdate

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new change1().setVisible(true);
        this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_jLabel4MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ssssss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel l5;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField t2;
    // End of variables declaration//GEN-END:variables

}
