/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Subtitutionfinal.java
 *
 * Created on Nov 7, 2013, 1:35:15 PM
 */

package mainpr;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER2
 */
public class Subtitutionfinal extends javax.swing.JFrame {
String s[];
int i;
    /** Creates new form Subtitutionfinal */
    public Subtitutionfinal()

    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        t1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/back-to-school8.jpg"))); // NOI18N
        jLabel1.setBounds(0, 0, 700, 470);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setText("Show TimeTable");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(40, 410, 130, -1);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.PALETTE_LAYER);

        jButton4.setText("Show Subs");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(200, 410, 120, -1);
        jLayeredPane1.add(jButton4, javax.swing.JLayeredPane.PALETTE_LAYER);

        table1.setBackground(new java.awt.Color(26, 145, 224));
        table1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        table1.setForeground(new java.awt.Color(112, 222, 250));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Period", "Class"
            }
        ));
        table1.setGridColor(new java.awt.Color(62, 118, 230));
        table1.setOpaque(false);
        jScrollPane4.setViewportView(table1);

        jScrollPane4.setBounds(30, 180, 290, 90);
        jLayeredPane1.add(jScrollPane4, javax.swing.JLayeredPane.PALETTE_LAYER);

        table2.setBackground(new java.awt.Color(26, 145, 224));
        table2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        table2.setForeground(new java.awt.Color(112, 222, 250));
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Period", "Teacher"
            }
        ));
        table2.setGridColor(new java.awt.Color(62, 118, 230));
        table2.setOpaque(false);
        jScrollPane3.setViewportView(table2);

        jScrollPane3.setBounds(380, 180, 280, 90);
        jLayeredPane1.add(jScrollPane3, javax.swing.JLayeredPane.PALETTE_LAYER);

        t1.setBackground(new java.awt.Color(240, 241, 242));
        t1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        t1.setForeground(new java.awt.Color(0, 153, 255));
        t1.setBorder(null);
        t1.setBounds(130, 80, 200, 20);
        jLayeredPane1.add(t1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel5.setForeground(new java.awt.Color(153, 204, 255));
        jLabel5.setText("Teachers' ID");
        jLabel5.setBounds(30, 80, 110, 20);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel6.setForeground(new java.awt.Color(153, 204, 255));
        jLabel6.setText("Time Table");
        jLabel6.setBounds(30, 150, 100, 14);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel4.setText("Subtitution");
        jLabel4.setBounds(460, 280, 73, -1);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel2.setForeground(new java.awt.Color(153, 204, 255));
        jLabel2.setText("Substitution");
        jLabel2.setBounds(380, 150, 100, 20);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.PALETTE_LAYER);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(360, 410, 90, -1);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.PALETTE_LAYER);

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monday", "TuesDay", "WednesDay", "ThursDay", "FriDay", "SaturDay", " " }));
        c1.setBounds(450, 80, 100, -1);
        jLayeredPane1.add(c1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel3.setForeground(new java.awt.Color(153, 205, 255));
        jLabel3.setText("Day");
        jLabel3.setBounds(380, 80, 60, -1);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/BACK.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jLabel7.setBounds(570, 340, 100, 100);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/tyu.PNG"))); // NOI18N
        jLabel8.setBounds(590, 10, 80, -1);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.PALETTE_LAYER);

        jButton2.setText("SET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(200, 370, 120, 30);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.MODAL_LAYER);

        jButton5.setText("Next");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(360, 370, 90, 30);
        jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.MODAL_LAYER);

        jButton6.setText("Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.setBounds(40, 370, 110, 30);
        jLayeredPane1.add(jButton6, javax.swing.JLayeredPane.MODAL_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String d=  (String) c1.getSelectedItem();
        ResultSet rs0=cons.startq("Select dayname(curdate());");
ResultSet rs1=cons.startq("select period,class from Timeu where tid="+t1.getText()+" And Day='"+d+"';");

DefaultTableModel dm=(DefaultTableModel)table1.getModel();
int a=dm.getRowCount();
while(a>0){
    a--;
dm.removeRow(a);
        }
table1.setModel(dm);
        try {
            while (rs1.next()) {


                String q=rs1.getString("Period");
                   String w=rs1.getString("Class");
                dm.addRow(new Object[]{q,w});
            }
        } catch (Exception e) {

        }
table1.setModel(dm);        // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

String d=  (String) c1.getSelectedItem();
DefaultTableModel dm=(DefaultTableModel)table2.getModel();
   int t=0;
   int a=dm.getRowCount();
while(a>0){
    a--;
dm.removeRow(a);
        }
table2.setModel(dm);
  String q="",p="";
        try {
            ResultSet rs2=cons.startq("Select * from Timeu where tid="+t1.getText()+" And Day='"+d+"';");
          while (rs2.next()) {
                ResultSet rs1=cons.startq("Select Distinct(tid) from TimeTable ;");
              t=0;
            p="NOt Found";
            q=rs2.getString("Period");
           if(rs2.getString("class").equals("Free"))
                    {
                         p="Free";

                    }


            else  {
                while(rs1.next()&&t==0)
                {
                    ResultSet rs3=cons.startq("Select * from  Timeu where tid="+rs1.getString("tid")+" and period="+q+" And Day='"+d+"';");

                    rs3.next();


                     if(rs3.getString("class").equals("Free"))
                    {

                         p = rs3.getString("tname");

                    s[i]=p;

                        System.out.print(p);

                    }
                }




              }
dm.addRow(new Object[]{q,p});
            }
        } catch (Exception e) {
           System.out.print(e.getMessage());
        }
   table2.setModel(dm);
                                     // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   int a=0;
        DefaultTableModel dm=(DefaultTableModel)table1.getModel();
      String d=  (String) c1.getSelectedItem();
      ResultSet rs=cons.startq("select * from td where tid="+t1.getText()+";");
        try {
            rs.next();
        } catch (Exception e) {
System.out.print(e);
        }
      while(a<4)
      {
//dm.get
          
     String f=(String) dm.getValueAt(a, 0);
              String f1=(String) dm.getValueAt(a, 1);

            try {

                cons.start("insert into timetable values("+ t1.getText() + ",'" + rs.getString("Fname") + "','" + d + "','" + f+ "','"+f1+"');");

System.out.print(d);

            } catch (Exception ex) {System.out.print(ex);}

a++;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       new FourWay().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       cons.start("create table Timeu(select*from TimeTable);");
        cons.start("create table substi(tid int,period varchar(20),Subs varchar(20));");
    }//GEN-LAST:event_formWindowActivated

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
 
    }//GEN-LAST:event_formWindowDeactivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int a=0;
         DefaultTableModel dm=(DefaultTableModel)table2.getModel();
        while(a<dm.getRowCount())
        {
    cons.start("insert into substi values("+t1.getText()+",'"+dm.getValueAt(a,0)+"','"+dm.getValueAt(a,1)+"');");
    cons.start("update timeu set class='Busy' where tname='"+dm.getValueAt(a,1)+"' and Period="+dm.getValueAt(a,0)+";" );
        a++;
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        DefaultTableModel dm=(DefaultTableModel)table2.getModel();
   int t=0;
   int a=dm.getRowCount();
while(a>0){
    a--;
dm.removeRow(a);
        }
table2.setModel(dm);

        DefaultTableModel dm1=(DefaultTableModel)table1.getModel();

   int a1=dm1.getRowCount();
while(a1>0){
    a1--;
dm1.removeRow(a);
        }
table1.setModel(dm1);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
cons.start("drop table substi;");
cons.start("drop table timeu;");
    }//GEN-LAST:event_formWindowClosed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
cons.startq("select * into outfile 'c:/Users/USER2/Desktop/subtitution.txt'  fields terminated by ','   lines terminated by '\n\r' from substi;");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subtitutionfinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField t1;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables

}
