/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * finalpay.java
 *
 * Created on Dec 27, 2013, 9:08:04 PM
 */
package newpackage;

import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class finalpay extends javax.swing.JFrame {
String ol="",ac1;
    /** Creates new form finalpay */
    public finalpay() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox();
        c2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        t4 = new javax.swing.JPasswordField();
        k1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Online Banking");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("16-Digit no.");
        jLabel1.setBounds(30, 100, 120, 20);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.PALETTE_LAYER);

        t1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t1CaretUpdate(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        t1.setBounds(190, 100, 210, 25);
        jLayeredPane1.add(t1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        t2.setBounds(190, 130, 210, 25);
        jLayeredPane1.add(t2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("Name on Card");
        jLabel2.setBounds(30, 130, 130, 20);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Expiry Date");
        jLabel3.setBounds(30, 170, 110, 20);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.PALETTE_LAYER);

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        c1.setBounds(190, 170, 70, 20);
        jLayeredPane1.add(c1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        c2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        c2.setBounds(300, 170, 90, 20);
        jLayeredPane1.add(c2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText(" /");
        jLabel4.setBounds(270, 170, 20, 20);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("VOC");
        jLabel5.setBounds(30, 220, 90, 20);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.PALETTE_LAYER);

        t3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t3CaretUpdate(evt);
            }
        });
        t3.setBounds(190, 220, 80, 25);
        jLayeredPane1.add(t3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        jLabel6.setForeground(new java.awt.Color(0, 102, 204));
        jLabel6.setText("PIN");
        jLabel6.setBounds(30, 260, 80, 20);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.PALETTE_LAYER);
        t5.setBounds(190, 360, 100, 25);
        jLayeredPane1.add(t5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        l3.setBounds(190, 300, 160, 50);
        jLayeredPane1.add(l3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        l1.setFont(new java.awt.Font("Colonna MT", 1, 36));
        l1.setForeground(new java.awt.Color(0, 102, 204));
        l1.setBounds(10, 0, 340, 60);
        jLayeredPane1.add(l1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        l2.setBounds(410, 10, 170, 90);
        jLayeredPane1.add(l2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("PAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(190, 410, 70, 30);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Write Code");
        jLabel7.setBounds(30, 360, 120, 30);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.PALETTE_LAYER);
        t4.setBounds(190, 260, 80, 25);
        jLayeredPane1.add(t4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        k1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        k1.setForeground(new java.awt.Color(0, 102, 204));
        k1.setBounds(30, 60, 300, 30);
        jLayeredPane1.add(k1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/histry.png"))); // NOI18N
        jLabel9.setBounds(0, 0, 590, 460);
        jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_t1ActionPerformed

private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed

}//GEN-LAST:event_t2ActionPerformed

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    String a = Pay.s;
    String s = Pay.d;
    l1.setText(a + "");
    String sd0 = "C:\\Users\\user\\Pictures\\visa.png";
    String sd1 = "C:\\Users\\user\\Pictures\\mas.png";
    if (s.equals("VISA")) {
        l2.setIcon(new ImageIcon(sd0));
    }
    if (s.equals("MASTER CARD")) {
        l2.setIcon(new ImageIcon(sd1));
    }
    int a1 = 0;
    a1 = (int) Math.round(Math.random() * 10);
    String sd = "C:\\Users\\user\\Pictures\\" + a1 + ".png";
    l3.setIcon(new ImageIcon(sd));
    int a7 = salary.a7;
    if (Salarydetails.aq.equals("") ^ true) {
        a7 = Integer.parseInt(Salarydetails.aq);
    }
    try {
        ResultSet rs = cons.startq("select * from capc where inde=" + a1 + ";");
        ResultSet rs1 = cons.startq("select* From bankac where tid=" + a7 + ";");
        rs.next();
        rs1.next();
        ac1 = rs1.getString("ac");
        k1.setText("Transferring to" + rs1.getString("ac"));
        ol = rs.getString("value");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex);
    }



}//GEN-LAST:event_formWindowActivated

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    String a = t1.getText();
    String b = t2.getText();
    String c = t3.getText();
    String d = t4.getText();
    String m = (String) c1.getSelectedItem();
    String y = (String) c2.getSelectedItem();
    int a7 = salary.a7;
    String a11 = salary.a11;
    String a12 = salary.a12;

    if (Salarydetails.aq.equals("") ^ true) {
        a11 = Salarydetails.aq2;
        a12 = Salarydetails.aq1;
        a7 = Integer.parseInt(Salarydetails.aq);
    }
    if (t5.getText().equals(ol)) {
        cons.start("insert into cap values('" + a + "','" + b + "','" + m + "-" + y + "',decode('" + d + "','qwerty')," + ac1 + ");");
        cons.start("update saldet set status='PAID' where tid=" + a7 + " and month='" + a12 + "' and year='" + a11 + "';");
        this.dispose();
        new mainfourway().setVisible(true);
    } else {
        JOptionPane.showMessageDialog(null, "Renter Captcha code rightly!", "WRONG ENTRY", 0);
    }

}//GEN-LAST:event_jButton1ActionPerformed

private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_c2ActionPerformed

private void t1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t1CaretUpdate
    cons.checkint(t1.getText());
    cons.checklength(t1.getText(), 16);
}//GEN-LAST:event_t1CaretUpdate

private void t3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t3CaretUpdate
    cons.checkint(t3.getText());
    cons.checklength(t3.getText(), 3);
}//GEN-LAST:event_t3CaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {



        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new finalpay().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c1;
    private javax.swing.JComboBox c2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel k1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JPasswordField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
