/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FourWay.java
 *
 * Created on Nov 11, 2013, 11:40:05 AM
 */
package newpackage;

/**
 *
 * @author USER2
 */
public class FourWay extends javax.swing.JFrame {

    
    static int jk = 0;

    /** Creates new form FourWay */
    public FourWay() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        j5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Information");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        l2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/teacher-icon.gif"))); // NOI18N
        l2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l2MouseExited(evt);
            }
        });
        l2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                l2MouseMoved(evt);
            }
        });
        l2.setBounds(380, 90, 94, 98);
        jLayeredPane1.add(l2, javax.swing.JLayeredPane.PALETTE_LAYER);

        l3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        l3.setForeground(new java.awt.Color(51, 51, 51));
        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/Delete Teacher.jpeg"))); // NOI18N
        l3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l3MouseExited(evt);
            }
        });
        l3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                l3MouseMoved(evt);
            }
        });
        l3.setBounds(370, 240, 102, 114);
        jLayeredPane1.add(l3, javax.swing.JLayeredPane.PALETTE_LAYER);

        l4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        l4.setForeground(new java.awt.Color(51, 51, 51));
        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/Search.jpeg"))); // NOI18N
        l4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l4MouseExited(evt);
            }
        });
        l4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                l4MouseMoved(evt);
            }
        });
        l4.setBounds(390, 400, 82, 109);
        jLayeredPane1.add(l4, javax.swing.JLayeredPane.PALETTE_LAYER);

        j3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18));
        j3.setForeground(new java.awt.Color(0, 153, 204));
        j3.setText("Save");
        j3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j3MouseMoved(evt);
            }
        });
        j3.setBounds(550, 110, 80, 60);
        jLayeredPane1.add(j3, javax.swing.JLayeredPane.PALETTE_LAYER);

        j4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18));
        j4.setForeground(new java.awt.Color(0, 153, 204));
        j4.setText("Delete");
        j4.setBounds(540, 240, 80, 110);
        jLayeredPane1.add(j4, javax.swing.JLayeredPane.PALETTE_LAYER);

        j5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18));
        j5.setForeground(new java.awt.Color(0, 153, 204));
        j5.setText("Search");
        j5.setBounds(540, 390, 80, 110);
        jLayeredPane1.add(j5, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/ghjk.jpg"))); // NOI18N
        jLabel3.setBounds(0, 0, 830, 600);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("jLabel5");
        jLabel5.setBounds(210, 250, 70, 30);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/tyu.PNG"))); // NOI18N
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jLabel18.setBounds(670, 20, 80, 72);
        jLayeredPane1.add(jLabel18, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/BACK.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jLabel25.setBounds(170, 380, 140, 120);
        jLayeredPane1.add(jLabel25, javax.swing.JLayeredPane.MODAL_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
        jk = 0;
        new mainframe().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l2MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
        jk = 1;
        new mainframe().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l3MouseClicked

    private void l4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseClicked
        jk = 2;
        new mainframe().setVisible(true);
    }//GEN-LAST:event_l4MouseClicked

    private void j3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_j3MouseMoved

    private void l2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseMoved
        j3.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_l2MouseMoved

    private void l3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseMoved
        j4.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_l3MouseMoved

    private void l4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseMoved
        j5.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_l4MouseMoved

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        j3.setVisible(false);
        j4.setVisible(false);
        j5.setVisible(false);
     
    }//GEN-LAST:event_formWindowActivated

    private void l2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseExited
        j3.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_l2MouseExited

    private void l3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseExited
        j4.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_l3MouseExited

    private void l4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseExited
        j5.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_l4MouseExited

private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
new ssi().setVisible(true);
this.dispose();
}//GEN-LAST:event_jLabel18MouseClicked

private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
new mainfourway().setVisible(true);
this.dispose();
}//GEN-LAST:event_jLabel25MouseClicked

 
   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FourWay().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    // End of variables declaration//GEN-END:variables
}
