/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * hra.java
 *
 * Created on Nov 11, 2013, 11:50:57 AM
 */
package newpackage;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author USER1
 */
public class hra extends javax.swing.JFrame {

    /** Creates new form hra */
    public hra() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        t4 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change Deductions");

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 2, 11));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/Save.jpg"))); // NOI18N
        jLabel5.setBounds(0, 0, 420, 390);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setBackground(java.awt.Color.white);
        jButton1.setText("SHOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(10, 350, 100, 23);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.PALETTE_LAYER);

        t4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 12));
        t4.setBorder(null);
        t4.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t4CaretUpdate(evt);
            }
        });
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        t4.setBounds(180, 230, 180, 20);
        jLayeredPane1.add(t4, javax.swing.JLayeredPane.PALETTE_LAYER);

        t3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 12));
        t3.setBorder(null);
        t3.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t3CaretUpdate(evt);
            }
        });
        t3.setBounds(180, 200, 180, 20);
        jLayeredPane1.add(t3, javax.swing.JLayeredPane.PALETTE_LAYER);

        t2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 12));
        t2.setBorder(null);
        t2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t2CaretUpdate(evt);
            }
        });
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        t2.setBounds(180, 170, 180, 20);
        jLayeredPane1.add(t2, javax.swing.JLayeredPane.PALETTE_LAYER);

        t1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 12));
        t1.setBorder(null);
        t1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t1CaretUpdate(evt);
            }
        });
        t1.setBounds(180, 140, 180, 20);
        jLayeredPane1.add(t1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24));
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText(" Change Allowence");
        jLabel1.setBounds(0, 0, 260, 70);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("House Rent Allowance");
        jLabel2.setBounds(10, 170, 133, 17);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Dearly Allowance");
        jLabel3.setBounds(10, 200, 102, 17);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel4.setForeground(new java.awt.Color(0, 102, 204));
        jLabel4.setText("Casual Leave");
        jLabel4.setBounds(10, 260, 100, 20);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.PALETTE_LAYER);

        jButton2.setBackground(java.awt.Color.white);
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(10, 320, 100, 23);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.PALETTE_LAYER);

        jButton3.setBackground(java.awt.Color.white);
        jButton3.setText("CLEAR ALL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(10, 290, 100, 23);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.PALETTE_LAYER);

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.setBounds(80, 10, 80, 80);
        jLayeredPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/tyu.PNG"))); // NOI18N
        jLabel6.setBounds(320, 20, 80, 72);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel8.setBackground(java.awt.Color.white);
        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel8.setForeground(new java.awt.Color(0, 102, 204));
        jLabel8.setText("Provident Fund");
        jLabel8.setBounds(10, 140, 91, 17);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/black.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jLabel9.setBounds(290, 280, 110, 100);
        jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel10.setBackground(java.awt.Color.white);
        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel10.setForeground(new java.awt.Color(0, 102, 204));
        jLabel10.setText("Insurance");
        jLabel10.setBounds(10, 230, 57, 20);
        jLayeredPane1.add(jLabel10, javax.swing.JLayeredPane.PALETTE_LAYER);

        t5.setFont(new java.awt.Font("Tempus Sans ITC", 3, 12));
        t5.setBorder(null);
        t5.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t5CaretUpdate(evt);
            }
        });
        t5.setBounds(180, 260, 180, 20);
        jLayeredPane1.add(t5, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ResultSet rs = cons.startq("select * from deduct;");
     
        try {
            rs.first();
            String a = rs.getString("pf");
            String b = rs.getString("hra");
            String c = rs.getString("da");
            String d = rs.getString("insurance");
            t1.setText(a);
            t2.setText(b);
            t3.setText(c);
            t4.setText(d);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        double a = Double.parseDouble(t1.getText());
        double b = Double.parseDouble(t2.getText());
        double c = Double.parseDouble(t3.getText());
        double d = Double.parseDouble(t4.getText());


        cons.start("truncate table deduct;");
        cons.start("Insert into deduct values('" + a + "','" + b + "','" + c + "','" + d + "');");


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

        new sett().setVisible(true);
        this.dispose();
}//GEN-LAST:event_jLabel9MouseClicked

private void t1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t1CaretUpdate
    cons.checkint(t1.getText());
    cons.checkvalue(t1.getText(), 100);
}//GEN-LAST:event_t1CaretUpdate

private void t2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t2CaretUpdate
    cons.checkint(t2.getText());
    cons.checkvalue(t2.getText(), 100);
}//GEN-LAST:event_t2CaretUpdate

private void t3CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t3CaretUpdate
    cons.checkint(t3.getText());
    cons.checkvalue(t3.getText(), 100);
}//GEN-LAST:event_t3CaretUpdate

private void t4CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t4CaretUpdate
    cons.checkint(t4.getText());
    cons.checkvalue(t4.getText(), 100);
}//GEN-LAST:event_t4CaretUpdate

private void t5CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t5CaretUpdate
    // TODO add your handling code here:
}//GEN-LAST:event_t5CaretUpdate

private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_t4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new hra().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
