package newpackage;

import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * leave.java
 *
 * Created on Oct 7, 2013, 11:37:57 AM
 */
/**
 *
 * @author USER1
 */
public class leave extends javax.swing.JFrame {

    /** Creates new form leave */
    public leave() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        t4 = new datechooser.beans.DateChooserCombo();
        t5 = new datechooser.beans.DateChooserCombo();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LEAVE DETAIL");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 102, 255));
        jLabel8.setText("        LEAVE ENTRY FORM");
        jLabel8.setBounds(70, 0, 371, 31);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("TEACHER ID");
        jLabel1.setBounds(30, 50, 90, 10);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        t1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t1CaretUpdate(evt);
            }
        });
        t1.setBounds(280, 40, 150, 20);
        jLayeredPane1.add(t1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("TEACHER NAME");
        jLabel2.setBounds(30, 80, 110, 10);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        t2.setBounds(280, 70, 150, 20);
        jLayeredPane1.add(t2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("FROM");
        jLabel4.setBounds(30, 140, 50, 10);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel5.setForeground(new java.awt.Color(204, 255, 204));
        jLabel5.setText("TO");
        jLabel5.setBounds(290, 140, 20, 17);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 204));
        jLabel6.setText("TYPE OF LEAVE");
        jLabel6.setBounds(30, 190, 110, 10);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CASUAL", "ILLNESS", "TOUR" }));
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        c1.setBounds(150, 180, 136, 20);
        jLayeredPane1.add(c1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        r1.setForeground(new java.awt.Color(51, 153, 0));
        r1.setText("FULL DAY");
        r1.setOpaque(false);
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        r1.setBounds(30, 100, 90, 20);
        jLayeredPane1.add(r1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        r2.setForeground(new java.awt.Color(51, 153, 0));
        r2.setText("HALF DAY");
        r2.setOpaque(false);
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        r2.setBounds(150, 100, 100, 20);
        jLayeredPane1.add(r2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(30, 250, 80, 30);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("NEW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(150, 250, 80, 30);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(270, 250, 70, 30);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/kath_school_holidays_570x320.jpg"))); // NOI18N
        jLabel7.setBounds(0, 0, 540, 320);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/tyu.PNG"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jLabel9.setBounds(450, 10, 80, 72);
        jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.PALETTE_LAYER);

        t4.setEnabled(false);
        t4.setBounds(110, 140, 155, 20);
        jLayeredPane1.add(t4, javax.swing.JLayeredPane.PALETTE_LAYER);

        t5.setEnabled(false);
        t5.setBounds(310, 140, 155, 20);
        jLayeredPane1.add(t5, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Software\\School\\project\\IMAGG\\BACKgh.png")); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jLabel3.setBounds(470, 260, 50, 50);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed

    }//GEN-LAST:event_c1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        this.dispose();
        new leave().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
cons.start("truncate table date;");
        String a = t1.getText();
        String b = t2.getText();
        int gh = 0;
        Calendar f,g;
        String d1, d2, m1, m2, y1, y2, dt1 = null, dt2 = null,r11,r21;
        String h = (String) c1.getSelectedItem();
         f = t4.getSelectedDate();
            g = t5.getSelectedDate();
            d1 = "" + (f.get(Calendar.DAY_OF_MONTH));
            d2 = "" + (g.get(Calendar.DAY_OF_MONTH));
            m1 = "" + (f.get(Calendar.MONTH) + 1);
            m2 = "" + (g.get(Calendar.MONTH) + 1);
            y1 = "" + (f.get(Calendar.YEAR));
            y2 = "" + (g.get(Calendar.YEAR));
            dt1 = y1 + "-" + m1 + "-" + d1;
            dt2 = y2 + "-" + m2 + "-" + d2;
              cons.start("insert into date values('"+dt2+"','"+dt1+"');");
        String r = null;
        ResultSet dfg=cons.startq("select * from date where d1<d2");
    try{    if(dfg.next()^true)
        {
        if (r1.isSelected()) {
            r = "full day";
           
          
            ResultSet rs=cons.startq("select d1-d2 from date;");
             try {
                rs.next();
int sd=rs.getInt("d1-d2");
System.out.print(sd);
String ht="d2+"+sd;
System.out.print(ht);
while (sd>=0)
{   ResultSet df=cons.startq("select "+ht+" from date;");
    df.next();
    ResultSet rsd=cons.startq("select * from leve where "+df.getString(ht)+ " between dfrom_mm_dd_yy and dto_mm_dd_yy and tid="+a+";");
    if(rsd.next())
    {
        JOptionPane.showMessageDialog(this,"Teacher might be allready leave on thease days.","Wrong entry",0);
     gh=1;
    
        break;

    }
 else
    {
     gh=0;
     }
     sd--;
}
                }
             catch (Exception e) {

            }

             
        }
        if (r2.isSelected()) {
            r = "half day";

            ResultSet ts=cons.startq("select tid from leve where curdate() between dfrom_mm_dd_yy and dto_mm_dd_yy and tid="+a+";");
            try {
                if (ts.next() ^ true) {
                    cons.start("insert into leve values(" + a + ",'" + b + "'," + dt1 + "," + dt2 + ",'" + h + "','" + r + "');");
                }
 else
     JOptionPane.showMessageDialog(this,"Teacher might be allready leave on thease days.","Wrong entry",0);
            } catch (Exception e) {

            }
        }
        if (gh==0)
        {
            cons.start("insert into leve values(" + a + ",'" + b + "','" + dt1 + "','" + dt2 + "','" + h + "','" + r + "');");
        }
        }
 else
     JOptionPane.showMessageDialog(this,"It is not Possible. ");
    }
    catch (Exception fd)
    {

    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      
    }//GEN-LAST:event_formWindowOpened

    private void t4OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_t4OnCommit
      
}//GEN-LAST:event_t4OnCommit

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
    t4.setEnabled(true);
    t5.setEnabled(true);
}//GEN-LAST:event_r1ActionPerformed

private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
    t4.setEnabled(false);
    t5.setEnabled(false);// TODO add your handling code here:
}//GEN-LAST:event_r2ActionPerformed

private void t1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t1CaretUpdate
    String gh = t1.getText();
    ResultSet rs = cons.startq("select * from td where tid=" + gh + ";");
    try {
        rs.next();
        t2.setText(rs.getString("Fname") + " " + rs.getString("lname"));
    } catch (Exception e) {
        t2.setText("Not Found");
    }

}//GEN-LAST:event_t1CaretUpdate

private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
new ssi().setVisible(true);
this.dispose();
}//GEN-LAST:event_jLabel9MouseClicked

private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
   new option2().setVisible(true);
        this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new leave().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private datechooser.beans.DateChooserCombo t4;
    private datechooser.beans.DateChooserCombo t5;
    // End of variables declaration//GEN-END:variables
}
