/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * loading.java
 *
 * Created on Oct 30, 2013, 12:28:39 PM
 */
package newpackage;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author USER2
 */
public class loading extends javax.swing.JFrame {

    int a = 0, b = 0;
    int delay = 5000;
    ActionListener taskPerformer;

    /** Creates new form loading */
    public loading() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pb = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        h = new javax.swing.JButton();
        l3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();

        pb.setBackground(new java.awt.Color(255, 255, 255));
        pb.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loading\n");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/qwer.png"))); // NOI18N
        jLabel1.setBounds(0, 0, 500, 250);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        h.setText("jButton2");
        h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hActionPerformed(evt);
            }
        });
        h.setBounds(90, 160, -1, -1);
        jLayeredPane1.add(h, javax.swing.JLayeredPane.DEFAULT_LAYER);

        l3.setBackground(new java.awt.Color(255, 255, 255));
        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/loading (1).gif"))); // NOI18N
        l3.setText("jLabel2");
        l3.setBounds(270, 0, 230, 270);
        jLayeredPane1.add(l3, javax.swing.JLayeredPane.PALETTE_LAYER);

        l1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18));
        l1.setForeground(new java.awt.Color(222, 13, 13));
        l1.setText("Loading ....");
        l1.setBounds(370, 210, 140, 30);
        jLayeredPane1.add(l1, javax.swing.JLayeredPane.POPUP_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        taskPerformer = new ActionListener() {

            public void actionPerformed(ActionEvent evt) {

                h.doClick();
                a++;
            }
        };
        new Timer(delay, taskPerformer).start();


    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    }//GEN-LAST:event_formWindowOpened

    private void hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hActionPerformed

        new Timer(delay, taskPerformer).setRepeats(false);
        new Timer(delay, taskPerformer).removeActionListener(taskPerformer);
        if (a < 1) {
            new ssssss().setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_hActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new loading().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton h;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l3;
    private javax.swing.JProgressBar pb;
    // End of variables declaration//GEN-END:variables
}
