/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainfourway.java
 *
 * Created on Jan 1, 2014, 6:21:20 PM
 */
package newpackage;
import sun.net.www.content.image.png;
import java.sql.ResultSet;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class mainfourway extends javax.swing.JFrame {

    /** Creates new form mainfourway */
    public mainfourway() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        l0 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        l0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/forwa.jpg"))); // NOI18N
        jLayeredPane1.add(l0);
        l0.setBounds(0, 0, 760, 780);

        l1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        l1.setForeground(new java.awt.Color(153, 51, 0));
        l1.setText("Information");
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
        });
        jLayeredPane1.add(l1);
        l1.setBounds(130, 250, 200, 90);
        jLayeredPane1.setLayer(l1, javax.swing.JLayeredPane.PALETTE_LAYER);

        l2.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        l2.setForeground(new java.awt.Color(0, 0, 153));
        l2.setText("Sallary");
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l2MouseEntered(evt);
            }
        });
        jLayeredPane1.add(l2);
        l2.setBounds(430, 210, 120, 100);
        jLayeredPane1.setLayer(l2, javax.swing.JLayeredPane.PALETTE_LAYER);

        l3.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        l3.setForeground(new java.awt.Color(204, 153, 0));
        l3.setText("Administration");
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l3MouseEntered(evt);
            }
        });
        jLayeredPane1.add(l3);
        l3.setBounds(410, 450, 240, 90);
        jLayeredPane1.setLayer(l3, javax.swing.JLayeredPane.PALETTE_LAYER);

        l4.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        l4.setForeground(new java.awt.Color(0, 102, 0));
        l4.setText("  Help");
        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l4MouseEntered(evt);
            }
        });
        jLayeredPane1.add(l4);
        l4.setBounds(210, 480, 150, 100);
        jLayeredPane1.setLayer(l4, javax.swing.JLayeredPane.PALETTE_LAYER);

        l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/Help_icon.png"))); // NOI18N
        l5.setText("\n");
        jLayeredPane1.add(l5);
        l5.setBounds(290, 320, 160, 130);
        jLayeredPane1.setLayer(l5, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void l1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseEntered
l5.setIcon(new ImageIcon("C:\\Users\\shaur\\Documents\\NetBeansProjects\\mainpr\\src\\mainpr\\information-1481584_960_720.png"));
//l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/mainpr/newpackage/help.png")));
}//GEN-LAST:event_l1MouseEntered

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

}//GEN-LAST:event_formWindowActivated

private void l2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseEntered
l5.setIcon(new ImageIcon("C:\\Users\\shaur\\Documents\\NetBeansProjects\\mainpr\\src\\mainpr\\salary-icon-3.png"));// TODO add your handling code here:
}//GEN-LAST:event_l2MouseEntered

private void l4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseEntered
l5.setIcon(new ImageIcon("C:\\Users\\shaur\\Documents\\NetBeansProjects\\mainpr\\src\\mainpr\\help.png"));// TODO add your handling code here:
}//GEN-LAST:event_l4MouseEntered

private void l3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseEntered
l5.setIcon(new ImageIcon("C:\\Users\\shaur\\Documents\\NetBeansProjects\\mainpr\\src\\mainpr\\mss-mssm-icon.png"));// TODO add your handling code here:
}//GEN-LAST:event_l3MouseEntered

private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
     new options().setVisible(true);
     this.dispose();
}//GEN-LAST:event_l2MouseClicked

private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
    this.dispose(); 
    new FourWay().setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_l1MouseClicked

private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
   new option2().setVisible(true);
   this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_l3MouseClicked

private void l4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseClicked

    new ssi().setVisible(true);
   this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_l4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainfourway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainfourway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainfourway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainfourway.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new mainfourway().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel l0;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    // End of variables declaration//GEN-END:variables
}
