/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainframe.java
 *
 * Created on Aug 16, 2013, 9:54:27 AM
 */
package newpackage;

import java.io.File;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author USER2
 */
public class mainframe extends javax.swing.JFrame {

    int a;
    int er = 2;
    String op, op1, sw, st, sm, post, dep;
    File file;

    /** Creates new form mainframe */
    public mainframe() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        c3 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        n3 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        n4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        n5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        n6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        n7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        n8 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        n9 = new javax.swing.JTextField();
        n11 = new javax.swing.JTextField();
        n10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        n0 = new javax.swing.JTextField();
        l20 = new javax.swing.JLabel();
        jif1 = new javax.swing.JInternalFrame();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        t1 = new javax.swing.JFileChooser();
        jButton5 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        b5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        r9 = new javax.swing.JRadioButton();
        r10 = new javax.swing.JRadioButton();
        r11 = new javax.swing.JRadioButton();
        r12 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        c4 = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        c5 = new javax.swing.JComboBox();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        qw = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        r7 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLayeredPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLayeredPane1.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 0));
        jLabel1.setText("First Name");
        jLabel1.setBounds(10, 50, 70, 17);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel2.setForeground(new java.awt.Color(102, 204, 0));
        jLabel2.setText("Last Name");
        jLabel2.setBounds(10, 80, 70, 17);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.PALETTE_LAYER);

        n1.setBorder(null);
        n1.setBounds(120, 50, 150, 20);
        jLayeredPane1.add(n1, javax.swing.JLayeredPane.PALETTE_LAYER);

        n2.setBorder(null);
        n2.setBounds(120, 80, 150, 20);
        jLayeredPane1.add(n2, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel3.setForeground(new java.awt.Color(102, 204, 0));
        jLabel3.setText("D.O.B");
        jLabel3.setBounds(10, 120, 40, 17);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.PALETTE_LAYER);

        c1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        c1.setForeground(new java.awt.Color(102, 153, 0));
        c1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        c1.setBounds(120, 120, 40, 23);
        jLayeredPane1.add(c1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel4.setForeground(new java.awt.Color(102, 204, 0));
        jLabel4.setText("//");
        jLabel4.setBounds(170, 120, 20, 17);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        c2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        c2.setForeground(new java.awt.Color(102, 153, 0));
        c2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC" }));
        c2.setBounds(200, 120, 60, 23);
        jLayeredPane1.add(c2, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel5.setForeground(new java.awt.Color(102, 204, 0));
        jLabel5.setText("//");
        jLabel5.setBounds(280, 120, 20, 17);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        c3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        c3.setForeground(new java.awt.Color(102, 153, 0));
        c3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", " ", " " }));
        c3.setBounds(300, 120, 60, 23);
        jLayeredPane1.add(c3, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel6.setForeground(new java.awt.Color(102, 204, 0));
        jLabel6.setText("Address");
        jLabel6.setBounds(10, 160, 60, 17);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.PALETTE_LAYER);

        n3.setColumns(20);
        n3.setRows(5);
        jScrollPane1.setViewportView(n3);

        jScrollPane1.setBounds(120, 160, 220, 90);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel7.setForeground(new java.awt.Color(102, 204, 0));
        jLabel7.setText("Gender");
        jLabel7.setBounds(10, 270, 50, 17);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.PALETTE_LAYER);

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        r1.setForeground(new java.awt.Color(102, 204, 0));
        r1.setText("Male");
        r1.setOpaque(false);
        r1.setBounds(120, 270, 60, 25);
        jLayeredPane1.add(r1, javax.swing.JLayeredPane.PALETTE_LAYER);

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        r2.setForeground(new java.awt.Color(102, 204, 0));
        r2.setText("Female");
        r2.setOpaque(false);
        r2.setBounds(220, 270, 80, 25);
        jLayeredPane1.add(r2, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel8.setForeground(new java.awt.Color(102, 204, 0));
        jLabel8.setText("Qualification");
        jLabel8.setBounds(10, 320, 80, 17);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.PALETTE_LAYER);

        n4.setBorder(null);
        n4.setBounds(250, 320, 150, 20);
        jLayeredPane1.add(n4, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel9.setForeground(new java.awt.Color(102, 204, 0));
        jLabel9.setText("High School from");
        jLabel9.setBounds(110, 320, 110, 17);
        jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel10.setForeground(new java.awt.Color(102, 204, 0));
        jLabel10.setText("Intermeddiate from");
        jLabel10.setBounds(110, 350, 120, 17);
        jLayeredPane1.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        n5.setBorder(null);
        n5.setBounds(250, 350, 150, 20);
        jLayeredPane1.add(n5, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel11.setForeground(new java.awt.Color(102, 204, 0));
        jLabel11.setText("Graduated from");
        jLabel11.setBounds(110, 380, 120, 17);
        jLayeredPane1.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        n6.setBorder(null);
        n6.setBounds(250, 380, 150, 20);
        jLayeredPane1.add(n6, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel12.setForeground(new java.awt.Color(102, 204, 0));
        jLabel12.setText("Post-Graduated from");
        jLabel12.setBounds(110, 410, 130, 17);
        jLayeredPane1.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        n7.setBorder(null);
        n7.setBounds(250, 410, 150, 20);
        jLayeredPane1.add(n7, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel13.setForeground(new java.awt.Color(102, 204, 0));
        jLabel13.setText("Extra");
        jLabel13.setBounds(110, 440, 60, 17);
        jLayeredPane1.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        n8.setBorder(null);
        n8.setBounds(250, 440, 150, 20);
        jLayeredPane1.add(n8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBounds(430, 10, 10, 590);
        jLayeredPane1.add(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel14.setForeground(new java.awt.Color(102, 204, 0));
        jLabel14.setText("Phone no.");
        jLabel14.setBounds(10, 480, 70, 17);
        jLayeredPane1.add(jLabel14, javax.swing.JLayeredPane.PALETTE_LAYER);

        n9.setBorder(null);
        n9.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                n9CaretUpdate(evt);
            }
        });
        n9.setBounds(120, 480, 150, 20);
        jLayeredPane1.add(n9, javax.swing.JLayeredPane.PALETTE_LAYER);

        n11.setBorder(null);
        n11.setBounds(540, 10, 150, 20);
        jLayeredPane1.add(n11, javax.swing.JLayeredPane.PALETTE_LAYER);

        n10.setBorder(null);
        n10.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                n10CaretUpdate(evt);
            }
        });
        n10.setBounds(120, 520, 150, 20);
        jLayeredPane1.add(n10, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel16.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel16.setForeground(new java.awt.Color(102, 204, 0));
        jLabel16.setText("Previous School");
        jLabel16.setBounds(440, 10, 100, 17);
        jLayeredPane1.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel18.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel18.setForeground(new java.awt.Color(102, 204, 0));
        jLabel18.setText("House");
        jLabel18.setBounds(440, 70, 60, 17);
        jLayeredPane1.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup2.add(r3);
        r3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        r3.setForeground(new java.awt.Color(102, 204, 0));
        r3.setText("Patel");
        r3.setOpaque(false);
        r3.setBounds(540, 70, 60, 25);
        jLayeredPane1.add(r3, javax.swing.JLayeredPane.PALETTE_LAYER);

        buttonGroup2.add(r4);
        r4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        r4.setForeground(new java.awt.Color(102, 204, 0));
        r4.setText("Tagore");
        r4.setOpaque(false);
        r4.setBounds(650, 70, 80, 25);
        jLayeredPane1.add(r4, javax.swing.JLayeredPane.PALETTE_LAYER);

        buttonGroup2.add(r5);
        r5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        r5.setForeground(new java.awt.Color(102, 204, 0));
        r5.setText("Vivakanand");
        r5.setOpaque(false);
        r5.setBounds(540, 110, 93, 25);
        jLayeredPane1.add(r5, javax.swing.JLayeredPane.PALETTE_LAYER);

        buttonGroup2.add(r6);
        r6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        r6.setForeground(new java.awt.Color(102, 204, 0));
        r6.setText("Bhagat");
        r6.setOpaque(false);
        r6.setBounds(650, 110, 65, 25);
        jLayeredPane1.add(r6, javax.swing.JLayeredPane.PALETTE_LAYER);

        b1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        b1.setForeground(new java.awt.Color(102, 153, 0));
        b1.setText("ADD");
        b1.setBorder(null);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        b1.setBounds(450, 360, 80, 30);
        jLayeredPane1.add(b1, javax.swing.JLayeredPane.PALETTE_LAYER);

        b2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        b2.setForeground(new java.awt.Color(102, 153, 0));
        b2.setText("Reset");
        b2.setBorder(null);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        b2.setBounds(540, 360, 80, 30);
        jLayeredPane1.add(b2, javax.swing.JLayeredPane.PALETTE_LAYER);

        b3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        b3.setForeground(new java.awt.Color(102, 153, 0));
        b3.setText("Exit");
        b3.setBorder(null);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        b3.setBounds(640, 360, 80, 30);
        jLayeredPane1.add(b3, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel19.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel19.setForeground(new java.awt.Color(102, 204, 0));
        jLabel19.setText("Employee I.D");
        jLabel19.setBounds(10, 20, 80, 17);
        jLayeredPane1.add(jLabel19, javax.swing.JLayeredPane.PALETTE_LAYER);

        n0.setBorder(null);
        n0.setBounds(120, 20, 150, 20);
        jLayeredPane1.add(n0, javax.swing.JLayeredPane.PALETTE_LAYER);

        l20.setBackground(new java.awt.Color(255, 153, 0));
        l20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10));
        l20.setForeground(new java.awt.Color(102, 204, 0));
        l20.setText(" INSERT PHOTO");
        l20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 0)));
        l20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l20MouseClicked(evt);
            }
        });
        l20.setBounds(300, 10, 90, 100);
        jLayeredPane1.add(l20, javax.swing.JLayeredPane.PALETTE_LAYER);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        t1.setBounds(0, 0, 630, 390);
        jLayeredPane2.add(t1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(480, 390, 60, 30);
        jLayeredPane2.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/great-abstract-wallpaper-hd.jpg"))); // NOI18N
        jLabel23.setBounds(0, 0, 640, 440);
        jLayeredPane2.add(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel27.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jLabel27.setBounds(570, 380, 50, 50);
        jLayeredPane2.add(jLabel27, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout jif1Layout = new javax.swing.GroupLayout(jif1.getContentPane());
        jif1.getContentPane().setLayout(jif1Layout);
        jif1Layout.setHorizontalGroup(
            jif1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        jif1Layout.setVerticalGroup(
            jif1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );

        jif1.setBounds(80, 20, 650, 470);
        jLayeredPane1.add(jif1, javax.swing.JLayeredPane.MODAL_LAYER);

        b5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        b5.setForeground(new java.awt.Color(102, 153, 0));
        b5.setText("Search");
        b5.setBorder(null);
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        b5.setBounds(450, 400, 80, 30);
        jLayeredPane1.add(b5, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel20.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel20.setForeground(new java.awt.Color(102, 204, 0));
        jLabel20.setText("Status");
        jLabel20.setBounds(440, 160, 35, 17);
        jLayeredPane1.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup4.add(r9);
        r9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        r9.setForeground(new java.awt.Color(102, 204, 0));
        r9.setText("Teaching");
        r9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/WINDOW.PNG"))); // NOI18N
        r9.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/WINDOW.PNG"))); // NOI18N
        r9.setOpaque(false);
        r9.setBounds(540, 160, 77, 25);
        jLayeredPane1.add(r9, javax.swing.JLayeredPane.PALETTE_LAYER);

        buttonGroup4.add(r10);
        r10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        r10.setForeground(new java.awt.Color(102, 204, 0));
        r10.setText("Non-Teaching");
        r10.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/WINDOW.PNG"))); // NOI18N
        r10.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/WINDOW.PNG"))); // NOI18N
        r10.setOpaque(false);
        r10.setBounds(650, 160, 111, 25);
        jLayeredPane1.add(r10, javax.swing.JLayeredPane.PALETTE_LAYER);

        buttonGroup3.add(r11);
        r11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        r11.setForeground(new java.awt.Color(102, 204, 0));
        r11.setText("Married");
        r11.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/WINDOW.PNG"))); // NOI18N
        r11.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/WINDOW.PNG"))); // NOI18N
        r11.setOpaque(false);
        r11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r11ActionPerformed(evt);
            }
        });
        r11.setBounds(540, 200, 71, 25);
        jLayeredPane1.add(r11, javax.swing.JLayeredPane.PALETTE_LAYER);

        buttonGroup3.add(r12);
        r12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        r12.setForeground(new java.awt.Color(102, 204, 0));
        r12.setText("Non-Married");
        r12.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/WINDOW.PNG"))); // NOI18N
        r12.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/WINDOW.PNG"))); // NOI18N
        r12.setOpaque(false);
        r12.setBounds(650, 200, 105, 25);
        jLayeredPane1.add(r12, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel21.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel21.setForeground(new java.awt.Color(102, 204, 0));
        jLabel21.setText("Post");
        jLabel21.setBounds(440, 230, 26, 17);
        jLayeredPane1.add(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        c4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        c4.setForeground(new java.awt.Color(102, 153, 0));
        c4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Principal", "Senior(Sec.) Teacher", "Junior(Sec.) Teacher", "Primary(Sec.) Teacher", "Accountant", " ", " " }));
        c4.setBounds(540, 230, 140, 23);
        jLayeredPane1.add(c4, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel22.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel22.setForeground(new java.awt.Color(102, 204, 0));
        jLabel22.setText("Department");
        jLabel22.setBounds(440, 300, 68, 17);
        jLayeredPane1.add(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        c5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        c5.setForeground(new java.awt.Color(102, 153, 0));
        c5.setBounds(540, 300, 140, 23);
        jLayeredPane1.add(c5, javax.swing.JLayeredPane.PALETTE_LAYER);

        b6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        b6.setForeground(new java.awt.Color(102, 153, 0));
        b6.setText("Delete");
        b6.setBorder(null);
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        b6.setBounds(540, 400, 80, 30);
        jLayeredPane1.add(b6, javax.swing.JLayeredPane.PALETTE_LAYER);

        b7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        b7.setForeground(new java.awt.Color(102, 153, 0));
        b7.setText("Update");
        b7.setBorder(null);
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        b7.setBounds(640, 400, 80, 30);
        jLayeredPane1.add(b7, javax.swing.JLayeredPane.PALETTE_LAYER);

        qw.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        qw.setForeground(new java.awt.Color(102, 153, 0));
        qw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/back-to-school-free-and-backgrounds-powerpoint-e.jpg"))); // NOI18N
        qw.setBounds(-30, -10, 830, 610);
        jLayeredPane1.add(qw, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jLabel25.setBounds(450, 470, 100, 0);
        jLayeredPane1.add(jLabel25, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel26.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel26.setForeground(new java.awt.Color(102, 204, 0));
        jLabel26.setText("Experience");
        jLabel26.setBounds(10, 500, 70, 70);
        jLayeredPane1.add(jLabel26, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/Next.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jLabel15.setBounds(690, 470, 100, 100);
        jLayeredPane1.add(jLabel15, javax.swing.JLayeredPane.PALETTE_LAYER);

        buttonGroup1.add(r7);
        r7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        r7.setForeground(new java.awt.Color(102, 204, 0));
        r7.setText("Male");
        r7.setOpaque(false);
        r7.setBounds(120, 270, 60, 25);
        jLayeredPane1.add(r7, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        this.dispose();
        new mainframe().setVisible(true);
    }//GEN-LAST:event_b2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        b1.setVisible(false);
        b2.setVisible(false);
        b3.setVisible(false);

        b5.setVisible(false);
        b6.setVisible(false);
        b7.setVisible(false);
      //  er =FourWay.jk;
        if (er == 0) {
            b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(true);

        }
        if (er == 1) {
            b6.setLocation(450, 360);
            b6.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(true);

        }
        if (er == 2) {
            b5.setLocation(450, 360);
            b7.setLocation(450, 400);
            b5.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(true);
            b7.setVisible(true);

        }
        DefaultComboBoxModel dm = (DefaultComboBoxModel) c5.getModel();
        DefaultComboBoxModel dm1 = (DefaultComboBoxModel) c4.getModel();
        String s;
        ResultSet rs1 = cons.startq("select*from post;");
        ResultSet rs = cons.startq("select*from dept;");
        dm.removeAllElements();
        dm1.removeAllElements();
        try {
            while (rs.next()) {
                s = rs.getString("depart");
                dm.addElement(s);
            }
            while (rs1.next()) {
                s = rs1.getString("post");
                dm1.addElement(s);
            }
        } catch (Exception e) {
        }
        c5.setModel(dm);
        c4.setModel(dm1);
    }//GEN-LAST:event_formWindowActivated

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        String q0 = n0.getText();
        String q1 = n1.getText();
        String q2 = n2.getText();
        String q3 = n3.getText();
        String q4 = n4.getText();
        String q5 = n5.getText();
        String q6 = n6.getText();
        String q7 = n7.getText();
        String q8 = n8.getText();
        String q9 = n9.getText();
        String q10 = n10.getText();
        String q11 = n11.getText();

        String cb, gen = null, gn = null;
        cb = (String) c3.getSelectedItem() + "-" + c2.getSelectedIndex() + "-" + (String) c1.getSelectedItem();
        if (r1.isSelected()) {
            gen = "M";
        }
        if (r2.isSelected()) {
            gen = "F";
        }
        if (r3.isSelected()) {
            gn = "Patel";
        }
        if (r3.isSelected()) {
            gn = "Tagore";
        }
        if (r5.isSelected()) {
            gn = "Vivekanand";
        }
        if (r6.isSelected()) {
            gn = "Baghat";
        }

        if (r9.isSelected()) {
            st = "Teaching";
        }
        if (r10.isSelected()) {
            st = "Non-Teaching";
        }
        if (r11.isSelected()) {
            sm = "Married";
        }
        if (r12.isSelected()) {
            sm = "Non-Married";
        }
        post = (String) c4.getSelectedItem();
        dep = (String) c5.getSelectedItem();
        try {
            Class.forName("java.sql.DriverManager");
            Connection c = (Connection) DriverManager.getConnection("jdbc:mySQL://localhost:3306/redfins", "root", "rrmps");
            Statement s = (Statement) c.createStatement();
            Statement s1 = (Statement) c.createStatement();
            String k = "insert into td values('" + q0 + "','" + q1 + "','" + q2 + "','" + cb + "','" + q3 + "','" + gen + "','" + q4 + "','" + q5 + "','" + q6 + "','" + q7 + "','" + q8 + "','" + q9 + "','" + q10 + "','" + q11 + "','" + gn + "','" + st + "','" + sm + "','" + post + "','" + dep + "');";
            s.executeUpdate(k);
            String k1 = "insert into picture values(" + q0 + ",'" + op + "')";
            s1.executeUpdate(k1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);

        }


    }//GEN-LAST:event_b1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        System.exit(0);         
    }//GEN-LAST:event_b3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     if(er==0)
     {
         try {
            Class.forName("java.sql.DriverManager");
            Connection c = (Connection) DriverManager.getConnection("jdbc:mySQL://localhost:3306/redfins", "root", "rrmps");
            Statement s = (Statement) c.createStatement();
            String k = "Select Max(tid) from td;";
            ResultSet rs = s.executeQuery(k);
            rs.first();
            int g = rs.getInt("Max(tid)");
            g = g + 1;
            n0.setText("" + g);

        } catch (Exception e) {

        }
        }
    }//GEN-LAST:event_formWindowOpened

    private void l20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l20MouseClicked
    jif1.setVisible(true);
    }//GEN-LAST:event_l20MouseClicked

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed

        file = t1.getSelectedFile();
        try {
          
            op = file.getAbsolutePath();
        } catch (Exception e) {
        }
       
        int a = 1, b = 0;
        String g, i = "";
        while (a <= op.length()) {
            g = op.substring(b, a);
            a++;
            b++;
            i = i.concat(g);
            if (g.equals("\\")) {

                i = i.concat("\\\\");
            }
        }
        op = i;
        System.out.print(op);
    }//GEN-LAST:event_t1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        l20.setIcon(new ImageIcon(op));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        String c, c1;
        String q0 = n0.getText();
        String q1q = n1.getText();
        String q2 = n2.getText();
        String q3 = n3.getText();
        String q4 = n4.getText();
        try {
            Class.forName("java.sql.DriverManager");
            Connection x = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/redfins", "root", "rrmps");
            Statement s = (Statement) x.createStatement();
            Statement s1 = (Statement) x.createStatement();
            String q = null; 
            if(q0.equals(""))
            {
            q = "select * from td where   FName like '%" + q1q + "%' And Lname like '%" + q2 + "%';";   
            }
           else
            q = "select * from td where tid like '" + q0 + "';";   
                
            String q1 = "select * from picture where tid like '" + q0 + "';";
            ResultSet rs = s.executeQuery(q);
            ResultSet rs1 = s1.executeQuery(q1);


            while (rs.next()) {
                n0.setText(rs.getString("tid"));
                n1.setText(rs.getString("Fname"));
                n2.setText(rs.getString("Lname"));
                n3.setText(rs.getString("Ad"));
                n4.setText(rs.getString("Q1"));
                n5.setText(rs.getString("Q2"));
                n6.setText(rs.getString("Q3"));
                n7.setText(rs.getString("Q4"));
                n8.setText(rs.getString("Q5"));
                n9.setText(rs.getString("Phn"));
                n10.setText(rs.getString("Exper"));
                n11.setText(rs.getString("Presc"));


              
                String h, h1,h3,hg;
                h = rs.getString("house");
                hg = rs.getString("Gender");
                h1 = rs.getString("st");
                h3 = rs.getString("sm");
                System.out.print(h+"    "+h1);
                if(hg.equals("M")) {
                  buttonGroup1.setSelected(r1.getModel(),true);
                   }
                if(hg.equals("F")) {
                  buttonGroup1.setSelected(r2.getModel(),true);
                   }
               if(h.equals("Vivekanand")) {
                   buttonGroup2.setSelected(r5.getModel(),true);
                   }
                if(h.equals("Baghat")) {
                    buttonGroup2.setSelected(r6.getModel(),true);
                }
                if(h.equals("Tagore")) {
                    buttonGroup2.setSelected(r4.getModel(),true);
                }
                if(h.equals("Patel")) {
                 buttonGroup2.setSelected(r3.getModel(),true);
                }
                if(h1.equals("Teaching")) {
                   buttonGroup4.setSelected(r9.getModel(),true);
                }
                if(h1.equals("Non-Teaching")) {
                      buttonGroup4.setSelected(r10.getModel(),true);
                }
                if(h3.equals("Married")) {
                  buttonGroup3.setSelected(r11.getModel(),true);
                }
                if(h3.equals("Non-Married")) {
                     buttonGroup3.setSelected(r12.getModel(),true);
                }
              



            }
            rs1.next();
             c1 = rs1.getString("Adr");
        
              l20.setIcon(new ImageIcon(c1));
        } catch (Exception e) {
        }

    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        cons.start("Delete from td where tid=" + n0.getText() + ";");
        cons.start("Delete from picture where tid=" + n0.getText() + ";");
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        String q0 = n0.getText();
        String q1 = n1.getText();
        String q2 = n2.getText();
        String q3 = n3.getText();
        String q4 = n4.getText();
        String q5 = n5.getText();
        String q6 = n6.getText();
        String q7 = n7.getText();
        String q8 = n8.getText();
        String q9 = n9.getText();
        String q10 = n10.getText();
        String q11 = n11.getText();
        String cb, gen = null, gn = null;


        cb = (String) c3.getSelectedItem() + "-" + c2.getSelectedIndex() + "-" + (String) c1.getSelectedItem();
        if (r1.isSelected()) {
            gen = "M";
        }
        if (r2.isSelected()) {
            gen = "F";
        }
        if (r3.isSelected()) {
            gn = "Patel";
        }
        if (r3.isSelected()) {
            gn = "Tagore";
        }
        if (r5.isSelected()) {
            gn = "Vivekanand";
        }
        if (r6.isSelected()) {
            gn = "Baghat";
        }

        if (r9.isSelected()) {
            st = "Teaching";
        }
        if (r10.isSelected()) {
            st = "Non-Teaching";
        }
        if (r11.isSelected()) {
            sm = "Married";
        }
        if (r12.isSelected()) {
            sm = "Non-Married";
        }
        post = (String) c4.getSelectedItem();
        dep = (String) c5.getSelectedItem();

        cons.start("delete from td where tid=" + q0 + ";");
        cons.start("Delete from picture where tid=" + n0.getText() + ";");
        cons.start("insert into picture values(" + q0 + ",'" + op + "')");
        cons.start("insert into td values('" + q0 + "','" + q1 + "','" + q2 + "','" + cb + "','" + q3 + "','" + gen + "','" + q4 + "','" + q5 + "','" + q6 + "','" + q7 + "','" + q8 + "','" + q9 + "','" + q10 + "','" + q11 + "','" + gn + "','" + st + "','" + sm + "','" + post + "','" + dep + "');");

    }//GEN-LAST:event_b7ActionPerformed

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        new FourWay().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel25MouseClicked

private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
   this.dispose();
    new salary().setVisible(true);

}//GEN-LAST:event_jLabel15MouseClicked

private void r11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r11ActionPerformed

}//GEN-LAST:event_r11ActionPerformed

private void n9CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_n9CaretUpdate
    cons.checkint(n9.getText());
    cons.checklength(n9.getText(), 10);
}//GEN-LAST:event_n9CaretUpdate

private void n10CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_n10CaretUpdate
    cons.checkint(n10.getText());
}//GEN-LAST:event_n10CaretUpdate

private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
 jif1.setVisible(false);     
}//GEN-LAST:event_jLabel27MouseClicked
   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new mainframe().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox c1;
    private javax.swing.JComboBox c2;
    private javax.swing.JComboBox c3;
    private javax.swing.JComboBox c4;
    private javax.swing.JComboBox c5;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JInternalFrame jif1;
    private javax.swing.JLabel l20;
    private javax.swing.JTextField n0;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n10;
    private javax.swing.JTextField n11;
    private javax.swing.JTextField n2;
    private javax.swing.JTextArea n3;
    private javax.swing.JTextField n4;
    private javax.swing.JTextField n5;
    private javax.swing.JTextField n6;
    private javax.swing.JTextField n7;
    private javax.swing.JTextField n8;
    private javax.swing.JTextField n9;
    private javax.swing.JLabel qw;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r10;
    private javax.swing.JRadioButton r11;
    private javax.swing.JRadioButton r12;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JRadioButton r9;
    private javax.swing.JFileChooser t1;
    // End of variables declaration//GEN-END:variables
}
