/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * options.java
 *
 * Created on Jan 2, 2014, 10:16:00 PM
 */
package newpackage;

/**
 *
 * @author user
 */
public class options extends javax.swing.JFrame {
static int jk=32;
    /** Creates new form options */
    public options() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        j8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        l2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/uo.png"))); // NOI18N
        l2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l2MouseExited(evt);
            }
        });
        l2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                l2MouseMoved(evt);
            }
        });
        l2.setBounds(330, 90, 150, 140);
        jLayeredPane1.add(l2, javax.swing.JLayeredPane.PALETTE_LAYER);

        l3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        l3.setForeground(new java.awt.Color(51, 51, 51));
        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/Salary-comparison-sites.png"))); // NOI18N
        l3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l3MouseExited(evt);
            }
        });
        l3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                l3MouseMoved(evt);
            }
        });
        l3.setBounds(320, 240, 180, 130);
        jLayeredPane1.add(l3, javax.swing.JLayeredPane.PALETTE_LAYER);

        j3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18));
        j3.setForeground(new java.awt.Color(0, 153, 204));
        j3.setText("Sallary Details");
        j3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j3MouseMoved(evt);
            }
        });
        j3.setBounds(530, 120, 130, 60);
        jLayeredPane1.add(j3, javax.swing.JLayeredPane.PALETTE_LAYER);

        j4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18));
        j4.setForeground(new java.awt.Color(0, 153, 204));
        j4.setText("Delete Sallary");
        j4.setBounds(530, 260, 150, 80);
        jLayeredPane1.add(j4, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/ghjk.jpg"))); // NOI18N
        jLabel3.setBounds(0, 0, 830, 600);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/images.jpeg"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jLabel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel4MouseMoved(evt);
            }
        });
        jLabel4.setBounds(330, 390, 102, 110);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.PALETTE_LAYER);

        j8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18));
        j8.setForeground(new java.awt.Color(0, 153, 204));
        j8.setText("Search Sallary");
        j8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j8MouseMoved(evt);
            }
        });
        j8.setBounds(530, 400, 160, 100);
        jLayeredPane1.add(j8, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/tyu.PNG"))); // NOI18N
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jLabel18.setBounds(690, 10, 80, 72);
        jLayeredPane1.add(jLabel18, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/BACK.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jLabel25.setBounds(180, 390, 100, 90);
        jLayeredPane1.add(jLabel25, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
        jk = 0;
        new Salarydetails().setVisible(true);
        this.dispose();
}//GEN-LAST:event_l2MouseClicked

private void l2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseExited
        j3.setVisible(false);        // TODO add your handling code here:
}//GEN-LAST:event_l2MouseExited

private void l2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseMoved
        j3.setVisible(true);     // TODO add your handling code here:
}//GEN-LAST:event_l2MouseMoved

private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
        jk = 1;
        new salary().setVisible(true);
        this.dispose();
}//GEN-LAST:event_l3MouseClicked

private void l3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseExited
        j4.setVisible(false);        // TODO add your handling code here:
}//GEN-LAST:event_l3MouseExited

private void l3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseMoved
        j4.setVisible(true);         // TODO add your handling code here:
}//GEN-LAST:event_l3MouseMoved

private void j3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j3MouseMoved
        // TODO add your handling code here:
}//GEN-LAST:event_j3MouseMoved

private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
jk=2;        this.dispose();
        new salary().setVisible(true);
}//GEN-LAST:event_jLabel4MouseClicked

private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        j8.setVisible(false);  
}//GEN-LAST:event_jLabel4MouseExited

private void jLabel4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseMoved
        j8.setVisible(true);  // TODO add your handling code here:
}//GEN-LAST:event_jLabel4MouseMoved

private void j8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j8MouseMoved
        // TODO add your handling code here:
}//GEN-LAST:event_j8MouseMoved

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
j3.setVisible(false);
    j4.setVisible(false);
    j8.setVisible(false);
}//GEN-LAST:event_formWindowActivated

private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
new ssi().setVisible(true);
this.dispose();
}//GEN-LAST:event_jLabel18MouseClicked

private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        new mainfourway().setVisible(true);
        this.dispose();// TODO add your handling code here:
}//GEN-LAST:event_jLabel25MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new options().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j8;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    // End of variables declaration//GEN-END:variables
}
