/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * option2.java
 *
 * Created on Jan 2, 2014, 10:33:56 PM
 */
package newpackage;

/**
 *
 * @author user
 */
public class option2 extends javax.swing.JFrame {

    /** Creates new form option2 */
    public option2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        j6 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        j7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administration");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/settings.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel2MouseMoved(evt);
            }
        });
        jLabel2.setBounds(380, 200, 130, 118);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.PALETTE_LAYER);

        j6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18));
        j6.setForeground(new java.awt.Color(0, 153, 204));
        j6.setText("Settings");
        j6.setBounds(570, 200, 90, 100);
        jLayeredPane1.add(j6, javax.swing.JLayeredPane.PALETTE_LAYER);

        l8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        l8.setForeground(new java.awt.Color(51, 51, 51));
        l8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/cal.jpg"))); // NOI18N
        l8.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        l8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l8MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l8MouseExited(evt);
            }
        });
        l8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                l8MouseMoved(evt);
            }
        });
        l8.setBounds(380, 340, 115, 120);
        jLayeredPane1.add(l8, javax.swing.JLayeredPane.PALETTE_LAYER);

        j2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18));
        j2.setForeground(new java.awt.Color(0, 153, 204));
        j2.setText("Subtitution");
        j2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j2MouseMoved(evt);
            }
        });
        j2.setBounds(570, 340, 110, 110);
        jLayeredPane1.add(j2, javax.swing.JLayeredPane.PALETTE_LAYER);

        l1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        l1.setForeground(new java.awt.Color(51, 51, 51));
        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/ghj.png"))); // NOI18N
        l1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        l1.setIconTextGap(6);
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
        });
        l1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                l1MouseMoved(evt);
            }
        });
        l1.setBounds(380, 90, 120, 100);
        jLayeredPane1.add(l1, javax.swing.JLayeredPane.PALETTE_LAYER);

        j1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18));
        j1.setForeground(new java.awt.Color(0, 153, 204));
        j1.setText("Back Up");
        j1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                j1MouseMoved(evt);
            }
        });
        j1.setBounds(570, 90, 100, 100);
        jLayeredPane1.add(j1, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel3.setForeground(new java.awt.Color(0, 153, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/ghjk.jpg"))); // NOI18N
        jLabel3.setBounds(0, 0, 830, 600);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/leave.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.setBounds(380, 470, 118, 118);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.PALETTE_LAYER);

        j7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18));
        j7.setForeground(new java.awt.Color(0, 153, 204));
        j7.setText("Leave");
        j7.setBounds(570, 500, 70, 50);
        jLayeredPane1.add(j7, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel5.setText("jLabel5");
        jLabel5.setBounds(210, 250, 70, 30);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/tyu.PNG"))); // NOI18N
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jLabel18.setBounds(720, 10, 80, 72);
        jLayeredPane1.add(jLabel18, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/BACK.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jLabel25.setBounds(180, 440, 100, 110);
        jLayeredPane1.add(jLabel25, javax.swing.JLayeredPane.MODAL_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
        new sett().setVisible(true);   // TODO add your handling code here:
}//GEN-LAST:event_jLabel2MouseClicked

private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        j6.setVisible(false);        // TODO add your handling code here:
}//GEN-LAST:event_jLabel2MouseExited

private void jLabel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseMoved
        j6.setVisible(true);         // TODO add your handling code here:
}//GEN-LAST:event_jLabel2MouseMoved

private void l8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseClicked
        this.dispose();
        new Subtitutionfinal().setVisible(true);

}//GEN-LAST:event_l8MouseClicked

private void l8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseExited
        j2.setVisible(false);        // TODO add your handling code here:
}//GEN-LAST:event_l8MouseExited

private void l8MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseMoved
        j2.setVisible(true);   // TODO add your handling code here:
}//GEN-LAST:event_l8MouseMoved

private void j2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j2MouseMoved
        // TODO add your handling code here:
}//GEN-LAST:event_j2MouseMoved

private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked

        new BackupFinal().setVisible(true);
        this.dispose();
}//GEN-LAST:event_l1MouseClicked

private void l1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseExited
        j1.setVisible(false);
}//GEN-LAST:event_l1MouseExited

private void l1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseMoved
        j1.setVisible(true);
}//GEN-LAST:event_l1MouseMoved

private void j1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j1MouseMoved
        l1.setVisible(true);
}//GEN-LAST:event_j1MouseMoved

private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        new leave().setVisible(true);
}//GEN-LAST:event_jLabel1MouseClicked

private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        j7.setVisible(false);         // TODO add your handling code here:
}//GEN-LAST:event_jLabel1MouseExited

private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        j7.setVisible(true);
}//GEN-LAST:event_jLabel1MouseMoved

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
j1.setVisible(false);
j2.setVisible(false);
j6.setVisible(false);
j7.setVisible(false);
}//GEN-LAST:event_formWindowActivated

private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
new ssi().setVisible(true);
this.dispose();
}//GEN-LAST:event_jLabel18MouseClicked

private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
new mainfourway().setVisible(true);
this.dispose();
}//GEN-LAST:event_jLabel25MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(option2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(option2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(option2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(option2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new option2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j6;
    private javax.swing.JLabel j7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l8;
    // End of variables declaration//GEN-END:variables
}
