/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pay.java
 *
 * Created on Dec 27, 2013, 8:20:21 PM
 */
package newpackage;

/**
 *
 * @author user
 */
public class Pay extends javax.swing.JFrame {

    static String s = "", d = "";

    /** Creates new form Pay */
    public Pay() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        r6 = new javax.swing.JRadioButton();
        r7 = new javax.swing.JRadioButton();
        r8 = new javax.swing.JRadioButton();
        r9 = new javax.swing.JRadioButton();
        r10 = new javax.swing.JRadioButton();
        l5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Online Transaction\n");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VISA");
        jLabel1.setBounds(40, 80, 40, 20);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DEBIT CARD");
        jLabel2.setBounds(10, 54, 80, 20);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator1.setBounds(80, 60, 370, 10);
        jLayeredPane1.add(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator2.setBounds(80, 90, 370, 10);
        jLayeredPane1.add(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Tahoma", 1, 11));
        r1.setForeground(new java.awt.Color(255, 255, 255));
        r1.setText("SBI");
        r1.setOpaque(false);
        r1.setBounds(80, 110, 70, -1);
        jLayeredPane1.add(r1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Tahoma", 1, 11));
        r2.setForeground(new java.awt.Color(255, 255, 255));
        r2.setText("CANARA");
        r2.setOpaque(false);
        r2.setBounds(170, 110, 80, -1);
        jLayeredPane1.add(r2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(r3);
        r3.setFont(new java.awt.Font("Tahoma", 1, 11));
        r3.setForeground(new java.awt.Color(255, 255, 255));
        r3.setText("HDFC");
        r3.setOpaque(false);
        r3.setBounds(270, 110, 70, -1);
        jLayeredPane1.add(r3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(r4);
        r4.setFont(new java.awt.Font("Tahoma", 1, 11));
        r4.setForeground(new java.awt.Color(255, 255, 255));
        r4.setText("BOI");
        r4.setOpaque(false);
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });
        r4.setBounds(80, 140, 70, -1);
        jLayeredPane1.add(r4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(r5);
        r5.setFont(new java.awt.Font("Tahoma", 1, 11));
        r5.setForeground(new java.awt.Color(255, 255, 255));
        r5.setText("PNB");
        r5.setOpaque(false);
        r5.setBounds(170, 140, 80, -1);
        jLayeredPane1.add(r5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mster Card");
        jLabel3.setBounds(40, 180, 70, 20);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator3.setBounds(110, 190, 340, 10);
        jLayeredPane1.add(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(r6);
        r6.setFont(new java.awt.Font("Tahoma", 1, 11));
        r6.setForeground(new java.awt.Color(255, 255, 255));
        r6.setText("BOI");
        r6.setOpaque(false);
        r6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6ActionPerformed(evt);
            }
        });
        r6.setBounds(80, 260, 70, -1);
        jLayeredPane1.add(r6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(r7);
        r7.setFont(new java.awt.Font("Tahoma", 1, 11));
        r7.setForeground(new java.awt.Color(255, 255, 255));
        r7.setText("SBI");
        r7.setOpaque(false);
        r7.setBounds(80, 230, 70, -1);
        jLayeredPane1.add(r7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(r8);
        r8.setFont(new java.awt.Font("Tahoma", 1, 11));
        r8.setForeground(new java.awt.Color(255, 255, 255));
        r8.setText("CANARA");
        r8.setOpaque(false);
        r8.setBounds(170, 230, 80, -1);
        jLayeredPane1.add(r8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(r9);
        r9.setFont(new java.awt.Font("Tahoma", 1, 11));
        r9.setForeground(new java.awt.Color(255, 255, 255));
        r9.setText("PNB");
        r9.setOpaque(false);
        r9.setBounds(170, 260, 80, -1);
        jLayeredPane1.add(r9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(r10);
        r10.setFont(new java.awt.Font("Tahoma", 1, 11));
        r10.setForeground(new java.awt.Color(255, 255, 255));
        r10.setText("HDFC");
        r10.setOpaque(false);
        r10.setBounds(270, 230, 70, -1);
        jLayeredPane1.add(r10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/Next.png"))); // NOI18N
        l5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l5MouseClicked(evt);
            }
        });
        l5.setBounds(340, 200, 100, 100);
        jLayeredPane1.add(l5, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\Online-Transaction-1216293.jpg")); // NOI18N
        jLabel6.setBounds(0, 0, 450, 310);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_r4ActionPerformed

private void r6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_r6ActionPerformed

private void l5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MouseClicked

    if (r1.isSelected()) {
        s = "State Bank of India";
        d = "VISA";
    }
    if (r2.isSelected()) {
        s = "Canara Bank";
        d = "VISA";
    }
    if (r3.isSelected()) {
        s = "HDFC";
        d = "VISA";
    }
    if (r4.isSelected()) {
        s = " Bank of India";
        d = "VISA";
    }
    if (r5.isSelected()) {
        s = "Punjab National Bank";
        d = "VISA";
    }
    if (r7.isSelected()) {
        s = "State Bank of India";
        d = "MASTER CARD";
    }
    if (r8.isSelected()) {
        s = "Canara Bank";
        d = "MASTER CARD";
    }
    if (r10.isSelected()) {
        s = "HDFC Bank";
        d = "MASTER CARD";
    }
    if (r6.isSelected()) {
        s = "Bank of India";
        d = "MASTER CARD";
    }
    if (r9.isSelected()) {
        s = "Punjab National Bank";
        d = "MASTER CARD";
    }
    new finalpay().setVisible(true);
    this.dispose();
}//GEN-LAST:event_l5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {



        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Pay().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel l5;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r10;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JRadioButton r8;
    private javax.swing.JRadioButton r9;
    // End of variables declaration//GEN-END:variables
}
