/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Salarydetails.java
 *
 * Created on Dec 27, 2013, 5:48:30 PM
 */
package newpackage;

import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Salarydetails extends javax.swing.JFrame {
static String aq="",aq1,aq2;
    /** Creates new form Salarydetails */
    public Salarydetails() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        t3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        b1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbutton = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Salary Details");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SALARY DETAILS");
        jLabel1.setBounds(20, 20, 320, 50);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        t1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                t1CaretUpdate(evt);
            }
        });
        t1.setBounds(150, 100, 60, 25);
        jLayeredPane1.add(t1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Basic Salary");
        jLabel2.setBounds(20, 140, 120, 20);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        t2.setBounds(150, 140, 110, 25);
        jLayeredPane1.add(t2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(500, 190, 80, 30);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        t3.setBounds(150, 180, 110, 25);
        jLayeredPane1.add(t3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Provident Fund");
        jLabel3.setBounds(20, 184, 110, 20);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        b1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Month", "Year", "Status", "Payment"
            }
        ));
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(b1);

        jScrollPane1.setBounds(10, 240, 452, 90);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/histry.png"))); // NOI18N
        jLabel4.setBounds(0, 0, 610, 340);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Teacher's ID");
        jLabel6.setBounds(20, 100, 130, 20);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.PALETTE_LAYER);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/tyu.PNG"))); // NOI18N
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jLabel18.setBounds(500, 10, 80, 72);
        jLayeredPane1.add(jLabel18, javax.swing.JLayeredPane.PALETTE_LAYER);

        lbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpr/BACK.png"))); // NOI18N
        lbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbuttonMouseClicked(evt);
            }
        });
        lbutton.setBounds(490, 230, 100, 100);
        jLayeredPane1.add(lbutton, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
aq=t1.getText();
ResultSet rs0=cons.startq("select*from Salary where tid="+t1.getText()+";");
ResultSet rs1=cons.startq("select sum(pf)  from pf1 group by tid having tid="+t1.getText()+";");
ResultSet rs2=cons.startq("select * from Saldet where tid="+t1.getText()+";");
DefaultTableModel dm=(DefaultTableModel) b1.getModel();
while(dm.getRowCount()>0)
{
    dm.removeRow(0);
    
}
String a,s,d,f;
try {
            rs0.next();
            rs1.next();
            while(rs2.next())
            {
                a=rs2.getString("month");
                 s=rs2.getString("year");
                 d=rs2.getString("status");
                 f=d.equals("PAID")?"":"PAY NOW";
                 dm.addRow(new Object[]{a,s,d,f});
            }
            t2.setText(rs0.getString("bsal"));
            t3.setText(rs1.getString("sum(pf)"));
        } catch (Exception e) {
           
        }
}//GEN-LAST:event_jButton1ActionPerformed

private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked
int a=b1.getSelectedRow();
int b=b1.getSelectedColumn();
aq1=    (String) b1.getValueAt(a, 0);
aq2=    (String) b1.getValueAt(a,1);
if(b1.getValueAt(a, b).equals("PAY NOW")){
         new Pay().setVisible(true);
         this.dispose();
}
}//GEN-LAST:event_b1MouseClicked

private void t1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_t1CaretUpdate
cons.checkint(t1.getText());
}//GEN-LAST:event_t1CaretUpdate

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
t2.setEditable(false);
t3.setEditable(false);
}//GEN-LAST:event_formWindowActivated

private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
new ssi().setVisible(true);
this.dispose();
}//GEN-LAST:event_jLabel18MouseClicked

private void lbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbuttonMouseClicked
       new options().setVisible(true);
       this.dispose();
}//GEN-LAST:event_lbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
  

      
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Salarydetails().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable b1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbutton;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
